# Covariates renaming

This notebook does a simple convertion of format for covariates, from underscore separated names to multiple columns in a .csv file.

In [1]:
import pandas as pd

In [2]:
dset = pd.read_csv("../data/conventional_namings_raw.csv", header=None)

In [3]:
dset = dset.rename(columns={0: "material", 1: "material_type"})

In [4]:
dset

   material material_type
0        G1     S_D_G_50N
1        G2     S_D_G_70N
2        G3    S_D_NG_50N
3        G4    S_D_NG_70N
4        G5     S_W_G_50N
5        G6     S_W_G_70N
6        G7    S_W_NG_50N
7        G8    S_W_NG_70N
8        G9    B_D_NG_50N
9       G10    B_D_NG_70N
10      G11     B_D_G_50N
11      G12     B_D_G_70N
12      G13    B_W_NG_50N
13      G14    B_W_NG_70N
14      G15    B _W_G_50N
15      G16    B_W_NG_70N
16      G17     N_D_G_50N
17      G18     N_D_G_70N
18      G19    N_D_NG_50N
19      G20    N_D_NG_70N
20      G21     N_W_G_50N
21      G22     N_W_G_70N
22      G23    N_W_NG_50N
23      G24    N_W_NG_70N

In [5]:
dset = dset.join(dset.material_type.str.split("_", expand=True)).drop(columns="material_type")
dset

   material   0  1   2    3
0        G1   S  D   G  50N
1        G2   S  D   G  70N
2        G3   S  D  NG  50N
3        G4   S  D  NG  70N
4        G5   S  W   G  50N
5        G6   S  W   G  70N
6        G7   S  W  NG  50N
7        G8   S  W  NG  70N
8        G9   B  D  NG  50N
9       G10   B  D  NG  70N
10      G11   B  D   G  50N
11      G12   B  D   G  70N
12      G13   B  W  NG  50N
13      G14   B  W  NG  70N
14      G15  B   W   G  50N
15      G16   B  W  NG  70N
16      G17   N  D   G  50N
17      G18   N  D   G  70N
18      G19   N  D  NG  50N
19      G20   N  D  NG  70N
20      G21   N  W   G  50N
21      G22   N  W   G  70N
22      G23   N  W  NG  50N
23      G24   N  W  NG  70N

In [6]:
dset[3] = dset[3].str[:-1].astype(int)

In [7]:
dset.columns = ["material", "material_type", "medium", "glazed", "force_N"]

In [8]:
dset

   material material_type medium glazed  force_N
0        G1             S      D      G       50
1        G2             S      D      G       70
2        G3             S      D     NG       50
3        G4             S      D     NG       70
4        G5             S      W      G       50
5        G6             S      W      G       70
6        G7             S      W     NG       50
7        G8             S      W     NG       70
8        G9             B      D     NG       50
9       G10             B      D     NG       70
10      G11             B      D      G       50
11      G12             B      D      G       70
12      G13             B      W     NG       50
13      G14             B      W     NG       70
14      G15            B       W      G       50
15      G16             B      W     NG       70
16      G17             N      D      G       50
17      G18             N      D      G       70
18      G19             N      D     NG       50
19      G20             N      D     NG       70
20      G21             N      W      G       50
21      G22             N      W      G       70
22      G23             N      W     NG       50
23      G24             N      W     NG       70

In [9]:
dset.to_csv("covariates.csv", index=False)